SectionLabel button, non-button 영역 분리 및 textColor 스펙 추가
channel-io/bezier-compose pull request #12
Opened 2024-05-24 04:11 UTC by kimdohun0104

- 기존 SectionLabel rightContents가 button, non-button 영역으로 분리되었습니다
  - ListItemContainer와 비슷한 스펙이지만, SectionLabel에선 두가지 영역을 동시에 사용할 수 있습니다.
- 아이콘 크기가 24로 커졌습니다. 기존 ListItemContainer와 동일한 사이즈로 정렬을 맞추기 위함입니다
- textColor 스펙이 추가되었습니다

2024-05-24 05:02 UTC, sodp5 requested changes

2024-05-24 05:07 UTC, kimdohun0104 commented on bezier/src/main/java/io/channel/bezier/component/SectionLabel.kt
> +                Spacer(modifier = Modifier.width(6.dp))
스크린샷은 웹 컴포넌트인 것 같습니다!  모바일 컴포넌트는 저것 하단에 있어요
<img width="814" alt="image" src="https://github.com/channel-io/bezier-compose/assets/36754680/0373a653-92e3-43d9-9bef-d8f49404d65f">

2024-05-24 07:20 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/component/SectionLabel.kt
> +                Spacer(modifier = Modifier.width(6.dp))
오 그렇네요 확인했습니다~!

2024-05-24 07:21 UTC, sodp5 approved these changes

2024-05-24 07:21 UTC, sodp5 requested changes
잠깐 걸어둘게요

2024-05-24 07:35 UTC, vvvvvoin submitted a review, later dismissed

2024-05-24 07:59 UTC, vvvvvoin requested changes

2024-05-24 07:59 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/component/SectionLabel.kt
> +                        color = textColor,
이 Text와 leftContents와 중간에 2dp가 존재하는데 확인 부탁드려요

2024-05-29 06:59 UTC, sodp5 commented
이 변경사항은 통화기록 피쳐에서만 반영하기로 했으므로 닫겠습니다!

2024-05-29 06:59 UTC, closed without merging