[MOB-293] 베지어 버튼 추가
channel-io/bezier-compose pull request #16
Opened 2024-05-31 08:31 UTC by sodp5

베지어 버튼을 추가합니다.

- 아직 아바타를 구현하지 않은 것과 이모지를 한정 짓는 케이스에 대한 스펙이 확정되지 않아서 우선 Painter만 받을 수 있도록 해두었습니다.
[[참고 스레드]](https://desk.channel.io/root/threads/groups/(CT)BezierRedesign-244958/6645bdc80dc3862acaa4/6657f0a15241645c6835)
- Pressed 상태의 색상 옵션도 리플과 함께 고려되어야 할 것 같아서 우선 이 부분도 제외해두었습니다.

<img width="1238" alt="image" src="https://github.com/channel-io/bezier-compose/assets/37904970/666300cd-75bf-4d7d-92d5-d903a6c32e5d">

2024-07-03 06:50 UTC, vvvvvoin requested changes

2024-07-03 06:50 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            )
maxlines, overflow 옵션도 있어야할거 같네요

2024-07-03 06:50 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            )
추가로 텍스트가 길어지면 suffixContent가 짤리는 것도 확인 부탁드려요

2024-07-03 06:50 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            )
너무 굵은 느김이여서 strokeWidth 값도 여쭤보면 좋을거 같아요
피그마보니 사이즈별로 크기가 바뀌는거 같네요

2024-07-03 06:50 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +
제거?!

2024-07-03 06:50 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +package io.channel.bezier.compose.component
임포트 최적화 부탁드립니다

2024-07-03 07:26 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            )
요건 임시로 들어간 Indicator라서 추후에 BezierProgress << 같은 것으로 변경될것 같습니다!

2024-07-05 07:29 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +
제거가 어떤 부분 제거 말씀주신걸까요??
혹시 공백이라면, IDE 셋팅상 추가되도록 되어있습니다!

2024-07-05 07:43 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            )
굿~ 수정했습니다

2024-07-10 06:32 UTC, vvvvvoin requested changes

2024-07-10 06:51 UTC, malibinYun requested changes

2024-07-10 06:51 UTC, malibinYun commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +sealed interface BezierButtonContent {
class, interface, enum 등 이 파일 내에서만 사용할 게 아닌 친구들은 파일 분리되면 좋겠어요.
이 파일에서 한 눈에 볼 수 있는 장점은 있겠으나, 이 파일에서 정말 관심 기울여서 봐야할 코드는 아니라고 생각해서요.

또, 파일 내에 Preview만 최하단에 위치하면 좋겠어요.
Preview가 있는 곳에 Button에서 사용해야할 중요한 코드가 있으면, (BezierButtonContent 같은) Preview를 위한 코드라는 인식이 들어서요.

2024-07-10 06:51 UTC, malibinYun commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            XLarge -> 24.dp
각 값들을 enum의 멤버로 갖는 것은 여전히 고려 대상이 아닐까요?

### 1. 매번 멤버의 값을 찾기 위해 when절을 사용하면, 중복되는 불필요한 코드가 길게 씌여 진다는 생각이 들어요.

멤버가 직접 값을 가짐으로써 중복되는 코드를 줄여낼 수 있을 거라 생각해요. 스크롤을 길게 내리지 않는 것으로 충분한 이점이라 생각해요.

### 2. BezierButtonSize가 가지는 값들을 한 눈에 보기는 어려워 보여요.

아래 처럼 적혀있다면, 스크롤을 길게 내리지 않더라도 이 enum이 포함하고 있는 멤버들의 목록을 index 처럼 한 눈에 볼 수 있다 생각해서요. 찾고자 하는 속성이 어느 enum에 위치하는지 빠르게 읽고 탐색할 수 있는 장점이 있다 생각해요.
```kotlin
enum Foo(
    val a: Int,
    val b: Int,
    val c: Int,
)
```

불필요한 반복적인 코드를 줄이고자 하는 니즈가 가장 큽니다.

2024-07-10 06:51 UTC, malibinYun commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +}
~이 구조는 저는 우려가 많이 되는데요,
enabled 이외에 pressed, focus, clickable 등등 다른 attribute가 추가되었을 때 대응하기에는 쉽지 않을 거란 생각이 들어요.~

뭔가 장황하게 느낀점들 써보려 했는데, 대안책이 생각이 잘 나지 않네요.
결국 많은 attribute 들에서 우선순위에 따른 색상을 선택해오는 객체는 필연적으로 생겨나겠다는 생각이 들어요.
이게 그 객체인 것일 뿐이라는 생각도 들구요.
나중에 더 많은 attribute들이 생겨났을 때, 이 내부를 어떻게 개선할 지 논의해보면 좋겠어요.

2024-07-10 06:51 UTC, malibinYun commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +    return when (variant) {
예전에는 각 속성이 서로 의존을 가지지 않으면 좋겠다고 생각했는데요,
버튼 Variants에 따라 버튼 Color가 바뀌는 것은 필연적이니, 개념상으로 의존 관계로 엮여있는 게 아닐까 하는 생각이 들어요.
그러니, BezierButtonColors에서 BezierButtonVariants 값을 받는 멤버가 있어도 좋겠어요.

혹은 Color enum 자체가 멤버로 variants의 값들을 가져도 괜찮다고 생각해요.
BezierButtonColors를 나타내는 객체이니, 실제 Color를 값들을 가지고 있는 것이 응집도를 높이는 방법이라 생각해서요.
```kotlin
enum class BezierButtonColors(
    val primaryColor: Color,
    val secondaryColor: Color,
    val tertiaryColor: Color,
) {

    fun getContentColor(variant: BezierButtonVariants): Color = when(variant) {
        BezierButtonVariants.Primary -> ~
        ....
    }

    ...
}
```

2024-07-10 06:51 UTC, malibinYun commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +    return when (variant) {
혹은 Variants가 각 ColorSet을 가지는 구조도 괜찮겠다는 생각이 들어요.

```kotlin
enum class BezierButtonVariants(
    private val colorSet: Map<BezierButtonColors, ColorSet>,
){

    Primary(
        mapOf(
            BezierButtonColors.Green to ColorSet(contentColor값, backgroundColor값)
        )
    ),
    ...

    fun getContentColor(color: BezierButtonColors) : Color{
        val colorSet = colorSet[color]
        return colorSet.contentColor
    }

    private class ColorSet(
        val contentColor: Color,
    ....
    )
}
```

2024-07-10 07:01 UTC, vvvvvoin approved these changes

2024-07-10 08:54 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +}
이 부분은 Material의 ButtonColors 구현체를 따라간 부분이었습니다!
ButtonColors 구현과 차이가 있는 이유는 아래 두 가지 이유였습니다.
- 확장성을 고려할 필요 없음
- disableColor는 0.4 alpha라는 규칙을 가짐

다만 disabled일 떄 무조건 alpha를 적용한다는 규칙이 있으니 color로 처리하기보다는 Root Layout Modifier에 alpha를 적용하는 방식으로 교체했습니다!
https://github.com/channel-io/bezier-compose/pull/16/commits/81e06bfecd7c7110f45eab1096bc49ab6d0e9b77

2024-07-10 13:23 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            XLarge -> 24.dp
Material3의 구현을 참고해서 개인적 해석으로 작성한 부분이었는데요!
- Material에서 정의된 enum에는 어떠한 속성도 넣지 않고 다른 파일에서 확장함수를 통해 속성(값)을 참조하도록 함

개인적인 해석으로는 Material에서는 enum에 구체적인 속성 값을 표현하기 보다는
set list의 역할만 부여하고 싶었다고 생각했습니다.

베지어로 예를 들면 베지어 사용자의 입장에서는 Xs, Xl 등이 어떤 속성을 가지는지 별로 궁금하지 않고
enum의 종류만 알고 싶을 것이라고 생각했어요. (여기서는 같은 파일에 정의해서 모호한 부분이 있지만요..!)

정확히 Material를 따라간다면 타입별로 Token Object를 정의하는 방법이 있을것 같은데,
경우의 수가 많은 저희 시스템에는 적합하지 않을것 같구
`ex)FilledButtonTokens, ColorSchemeKeyTokens`

enum의 함수로 데이터 셋 클래스를 리턴하게 하는 함수를 추가하는 방법도 있을것 같은데 보일러플레이트가 너무 늘어날 것 같아서 이건 피하고 싶네요!

요 부분 포함해서 생각해도 enum에 멤버를 추가하는 편이 더 좋다고 생각하실까용?
일단 기존 의도는 이러했고 어느 방법이든 컨선은 없습니다!

2024-07-11 04:53 UTC, malibinYun commented
파일 분리 코멘트는 사실 각각 class, interface 마다 분리하자는 의미었어요!
package로 properties 구분하고, 하위에 파일들 모두 포함하면 좋겠다는 생각이었어요.

2024-07-11 05:09 UTC, malibinYun commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            XLarge -> 24.dp
오 요거 저번에 이야기 나누면서 이해했던 것 같은데, 다시 보니까 구체적인 코드가 잘 안떠오르네요..
혹시 짧게 코드로 표현해주실 수 있으실까요 ㅎㅎ,......

2024-07-11 05:17 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            XLarge -> 24.dp
```kotlin
enum class BezierButtonSize {
    XsSmall,
    Small,
    Medium,
    Large,
    XLarge;
}

fun BezierButtonSize.toProperties(): BezierButtonSizeProperties {
    return // BezierButtonSizeProperties(...)
}

data class BezierButtonSizeProperties(
        val textStyle: TextStyle,
        val radius: Dp,
        val containerPadding: PaddingValues,
        val textPadding: PaddingValues,
        val iconSize: PaddingValues,
)
```
Material3 FilledButtonTokens 같은 게 이런 느낌으로 구현되어 있는것 같다고 느꼈습니다!

2024-07-12 06:46 UTC, malibinYun commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            XLarge -> 24.dp
enum에 넣는 게 응집도를 가장 높일 수 있는 방법이라 생각이 들어요!
사용 편의를 위한다면 이런 방법으로 짜야할 것 같은데, 이런 형태 괜찮다면 enum에 멤버 넣는 것으로 선택되면 좋겠다는 게 제 바람입니다 ㅎㅎ..

```kotlin
enum class ButtonSize{
    private val internalTextStyle: @Composable () -> TextStyle,
) {
    Medium(
        internalTextStyle = { BezierTheme.typography.body2SemiBold }
    )
    ;

    val textStyle: TextStyle @Composable get() = internalTextStyle()
}
```

2024-07-12 06:54 UTC, malibinYun commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            XLarge -> 24.dp
구두로 람다를 호출하기 위한 괄호 사용은 OK.
위 같은 편의성 제공을 위한 메서드는 보일러 플레이트 코드를 늘리는 형태임. 위 제안된 코드를 작성하는 형태는 없을 가능성이 높음.

저는 enum 멤버에 넣는 것에 한 표입니다!

2024-07-15 04:52 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            XLarge -> 24.dp
저는 이넘 필드이거나 함수인거는 개인 취향에 따라서 달라질 수 있다고 생각합니다.
다만, 이넘 필드에 @Composable -> Any 가 들어가는 형태만 피했으면 합니다. 현재는 사이즈 혹은 컬러(@Composable -> Color)에 들어가도 크게 어색한점은 없을거 같은데, 이후부터 여기에는 어떤 컴포저블 함수가 사용될 수 있다라는 느낌이 들거 같아요. 

예를들어 이넘에 따라 달라지는 컴포넌트 형태를 구현하기 위해 컴포저블 함수를 필드에 넣게 될거 같아요. 아래 같은 형태는 이후 변경사항에 대한 부분들 챙길 때 읽기 어려운 코드 형태가 될거 같아요. (A에 새로운 파라미터가 추가되면 B에도 영향이 가기 때문에 B에도 의미없는 값을 넣어야하는 불필요한 형태이면서 B에서는 그 필드가 안쓰이고 있다는걸 파악해야하는 등등)
```kotlin
enum class Foo(
        val bar: @Composable (textField: String) -> Unit,
) {
    A(
            bar = { androidx.compose.material.Text(text = textField) },
    ),
    B(
            bar = { androidx.compose.material.Text(text = "2") }, // not use textField
    ),
}
```
특정 부분에서만 예외를 두겠다는 것은 저희가 유지보수하기에 어렵고 일괄성없는 형태가 될거 같아요. 컬러, 스타일 등등 에 매번 대응하는 것보다 쓰지 말자로 관리에는 편하다고 생각해서요.

2024-07-17 07:07 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierButton.kt
> +            XLarge -> 24.dp
구두로 정리한 내용 남겨둡니다!
- enum에서 UI를 그리는 Composable 함수를 만들지 않는다. Preview를 볼 수 없고 속성을 보고 어떤 UI가 그려질지 예측하기 어렵다.
- Color를 반환하는 Composable 함수는 허용한다.
- 사용되지 않는 파라미가 있을 때는 enum이 아니라 sealed class로 정의한다.
- enum 하위에 `when(this)`가 들어가는 Property를 정의하지 않는다. 생성자에 정의하는 일관성을 가져간다.

2024-07-22 08:16 UTC, malibinYun approved these changes

2024-07-24 05:32 UTC, vvvvvoin approved these changes

2024-07-24 05:32 UTC, merged