[MOB-960] Spinner 추가
channel-io/bezier-compose pull request #29
Opened 2024-07-05 10:15 UTC by sodp5

Spinner 컴포넌트를 추가했습니다.

https://github.com/channel-io/bezier-compose/assets/37904970/ca991b44-7675-4a43-bca5-777d69a81eb7

2024-07-08 08:03 UTC, vvvvvoin requested changes

2024-07-08 08:03 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/BezierLoader.kt
> +@Preview(showBackground = true)
진짜 상관없을거 같은데 프리뷰 onOverlay가 잘 안보이는데 배경색을 회색으로 줘도 괜찮을거 같네요.

2024-07-10 07:01 UTC, vvvvvoin approved these changes

2024-07-22 11:01 UTC, sodp5 commented
https://github.com/channel-io/bezier-compose/pull/16#discussion_r1680534727
여기 룰 따라서 로더도 수정했습니다!

2024-07-24 05:33 UTC, merged