[MOB-1666] Status 컴포넌트 구현
channel-io/bezier-compose pull request #42
Opened 2024-07-30 07:41 UTC by sodp5

Status 컴포넌트를 구현합니다.

figma: https://www.figma.com/design/KyhPPZeeC0JBmTclJGe3nn/Status?node-id=6-34&t=hy7HIjbvb2tie8Up-4

![image](https://github.com/user-attachments/assets/23c4822c-b109-4f4e-9aa9-e7409222757f)
![image](https://github.com/user-attachments/assets/02342c20-6171-430b-929b-007a7c5a5333)

2024-07-31 14:46 UTC, vvvvvoin requested changes

2024-07-31 14:46 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/chat/BezierChatBadge.kt
> +        modifier: Modifier = Modifier,
modifier가 필요한 부분일까요? 임의로 변경하면 사이즈가 조절되서 표시되는데 의도된 방향은 아닐거 같아서요.
```kotlin
BezierChatBadge(
        badgeSize = Medium,
        modifier = Modifier.size(40.dp)
)
```
<img width="683" alt="image" src="https://github.com/user-attachments/assets/6406b45e-e58f-4bf8-a8d6-0e403d7a40ad">

2024-07-31 14:46 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/status/BezierStatusBadge.kt
> +        badgeSize: BezierStatusBadgeSize,
기존에 단순하게 표현한거 같아서?
```suggestion
        size: BezierStatusBadgeSize,
```

2024-07-31 14:46 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/chat/BezierChatBadge.kt
> +        badgeSize: BezierChatBadgeSize,
기존에 단순하게 표현한거 같아서?
```suggestion
        size: BezierChatBadgeSize,
```

2024-07-31 14:46 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/status/BezierStatusBadge.kt
> +        modifier: Modifier = Modifier,
이 modifier어도 ChatBadge와 동일할거 같아요.

2024-07-31 14:46 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/status/properties/BezierStatusBadgeSize.kt
> +        internal val moonSize: Dp,
아이콘 사이즈로 별도로 가져가는건 어색할까요?

2024-08-01 03:54 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/status/properties/BezierStatusBadgeSize.kt
> +        internal val moonSize: Dp,
어떤 식으로 생각하신걸까요?? 혹시 예시를 조금 써주실 수 있을까요?
두 값이 달라서 분리되어야한다고 생각했어요

2024-08-01 03:58 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/chat/BezierChatBadge.kt
> +        modifier: Modifier = Modifier,
size 같은 경우가 조금 고민되긴 한데 modifier에 배치와 관련된 함수들 등 modifier가 매개변수로 제공되지 않으면 굉장히 불편할 것 같아요
e.g. padding, offset, align, ...
그래서 Modifier는 모든 컴포넌트에 추가하는 게 좋다고 생각하고 있습니다

또, size값에 default 값이 없어서 modifier에 사이즈를 넣는 경우는 없을 것 같아서 괜찮을 것 같기도 해요 (피그마 따라 구현할테니까)

2024-08-01 04:33 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/status/properties/BezierStatusBadgeSize.kt
> +        internal val moonSize: Dp,
dot, moon 도 같은 icon으로 보고 사용하면 어떤지에 대한 부분입니다

2024-08-01 04:42 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/chat/BezierChatBadge.kt
> +        modifier: Modifier = Modifier,
불편한 점이 어떤 부분인지 이해가는데, 컴포넌트 자체의 크기가 변경되면 안된다고 생각해요. material Switch, Checbox같은 경우도 Modifier.size를 변경해도 컴포넌트 자체의 영역은 변하지 않게 구현이 되어 있어요.
```kotlin
Checkbox(checked = false, onCheckedChange = {}, modifier = Modifier.size(75.dp))
Checkbox(checked = true, onCheckedChange = {}, modifier = Modifier.size(75.dp))
Switch(checked = false, onCheckedChange = {}, modifier = Modifier.size(75.dp))
Switch(checked = true, onCheckedChange = {}, modifier = Modifier.size(75.dp))
```
<img width="443" alt="image" src="https://github.com/user-attachments/assets/bc129bce-8b30-4cf5-b9c3-7559ae310b4f">

그래서 BezierStatusBadge.Box 의 modifier에 size대신 requiredSize 사이즈를 쓰는걸로 해결할 수 있을거 같아요.
```kotlin
BezierStatusBadgeSize.entries.forEach {
    BezierStatusBadge(
            modifier = Modifier.size(50.dp).background(Color.Red),
            isOnline = true,
            doNotDisturb = true,
            badgeSize = it,
    )
    BezierStatusBadge(
            isOnline = false,
            doNotDisturb = true,
            badgeSize = it,
    )
}
```
<img width="814" alt="image" src="https://github.com/user-attachments/assets/4143f96e-d391-492c-80c9-3c1b5c331ba5">

2024-08-01 07:30 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/chat/BezierChatBadge.kt
> +        modifier: Modifier = Modifier,
좋은데요!

2024-08-02 08:00 UTC, merged