아바타 컴포넌트 구현
channel-io/bezier-compose pull request #43
Opened 2024-07-30 13:11 UTC by sodp5

아바타 컴포넌트를 추가합니다.

아래 두 pr이 머지되기 전까지 Draft로 올려둡니다.
- https://github.com/channel-io/bezier-compose/pull/41
- https://github.com/channel-io/bezier-compose/pull/42

figma: https://www.figma.com/design/aJJF4bU82uR0jAsmWp5wlE/Navigation?node-id=1-19155&t=XjZiAU7MEDWP1i0n-4

[확대 이미지]
![image](https://github.com/user-attachments/assets/3ca8bc70-c134-40eb-8e99-70fe964949fc)

[전체 이미지]
![image](https://github.com/user-attachments/assets/42ddd140-1fa5-4180-ac70-b1eabd2d470b)

2024-08-05 10:47 UTC, vvvvvoin requested changes

2024-08-05 10:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        avatarSize: BezierAvatarSize,
이전 뱃지와 동일하게 size로 하면 어떠신가요?
```suggestion
        size: BezierAvatarSize,
```

2024-08-05 10:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        badge: BezierAvatarBadge = BezierAvatarBadge.None,
편의기능으로 online, doNotDisturb만 따로 받는걸 만드시는건 어떠신가요?
사용할 때 class면 자동 완성에 표시가 잘 안되기도 해서요. 이넘으로 만들기에는 너무 많이 만들거 같아서요.

잘 표시안된다는건 아래 같은 경우입니다.
<img width="604" alt="image" src="https://github.com/user-attachments/assets/35804086-1056-401f-908a-abd94d88dbd6">

2024-08-05 10:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/properties/BezierAvatarSize.kt
> +            outlineBorderWidth = 2.dp,
```suggestion
            outlineBorderWidth = 4.dp,
```

2024-08-05 10:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +}
아바타 사이즈 24일때는 IntegrationBadge 가 그냥 원형인데 확인부탁드려요

2024-08-06 08:49 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        badge: BezierAvatarBadge = BezierAvatarBadge.None,
이 경우에는 badge에 status로 되어있어서 online, dnd 변수가 있으면 오히려 사용하기 헷갈릴 수도 있을것 같아서 여기서는
추가 안해도 될것 같은데 어떻게 생각하시나요??

<img width="406" alt="image" src="https://github.com/user-attachments/assets/4d39bc01-7888-4a25-8a4b-fb44258a6749">

2024-08-06 10:05 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        badge: BezierAvatarBadge = BezierAvatarBadge.None,
처음 사용하는 개발자 입장에서는 헷갈릴 수 있을거 같아요.근데 Status 값들 중에 isOnline, doNotDisturb는 피그마에 명시된게 없는데 이 또한 여지는 남아있는거 같아요.
그리고 추후 도메인을 알게 되면 매번 생성해서 사용하는 것 보다 더 편리하게 사용하지 않을까 해서요.
```kotlin
val managerOnlineItem = getManager()

Avatart(
    isOnline = managerOnlineItem.online != null,
    doNotDisturb = managerOnlineItem.manager.doNotDisturb,
)

val bezierAvatarChatBadge = BezierAvatarBadge.Chat(managerOnlineItem.online != null, managerOnlineItem.manager.doNotDisturb)

Avatart(
    status = bezierAvatarChatBadge,
)
```

2024-08-06 10:08 UTC, vvvvvoin requested changes

2024-08-06 10:08 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/properties/BezierAvatarBadge.kt
> +        fun createShape(size: BezierAvatarSize): Shape {
진짜 진짜 잘 몰라서 남겨요.
이런 코드가 모메가 피하고자 했더 방식이 아닌가해서요...!

2024-08-07 06:17 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/properties/BezierAvatarBadge.kt
> +        fun createShape(size: BezierAvatarSize): Shape {
when(this) 를 피하기로 했던거고 Shape가 size에 종속되어서 만들어지다보니 이 경우는 그 때 하기로 한 사례랑 동일한것 같아요
버튼에서 color에 variant 넣는 부분입니다!

2024-08-07 07:24 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        badge: BezierAvatarBadge = BezierAvatarBadge.None,
옙! 요건 추가했고 너무 많아지는 경우가 약간 걱정되긴 한데
지금은 4개밖에 안돼서 이정도는 괜찮을것 같으니 더 늘어나게 되면 명확한 정책을 정해보시죠!

2024-08-07 07:35 UTC, vvvvvoin approved these changes

2024-08-07 07:35 UTC, merged