[MOB-1676] 버튼 미구현 컨텐츠 구현
channel-io/bezier-compose pull request #45
Opened 2024-07-31 05:53 UTC by sodp5

Loader, Avatar, Emoji 값을 적용합니다.

figma: https://www.figma.com/design/8J76noM3T1Sp5cNPhnYQiG/Action?node-id=112-6059&t=PeOyStx7eyqPnUpD-4

<img width="420" alt="image" src="https://github.com/user-attachments/assets/b88f4bbe-755e-4c52-acc0-170914875229">
<img width="455" alt="image" src="https://github.com/user-attachments/assets/a394c93b-032e-4a18-9879-3daf99809c7a">

2024-08-07 14:35 UTC, vvvvvoin requested changes

2024-08-07 14:35 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/button/properties/BezierButtonSize.kt
> +        internal val avatarSize: BezierAvatarSize,
이 수치들은 따로 피그마 권한으로만 볼 수 있느건가요?

2024-08-08 01:30 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/button/properties/BezierButtonSize.kt
> +        internal val avatarSize: BezierAvatarSize,
이쪽 스레드 내용 보고 넣은거였어요!
여기에 들어가는 값은 16/20/24 고 없으면 variants에 추가되어야함 으로 이해했어서용
https://desk.channel.io/root/threads/groups/(CT)BezierRedesign-244958/66a9c7f6c49bd5d51d75/66b3087b0bf3451de5b6

2024-08-12 07:12 UTC, vvvvvoin approved these changes

2024-08-12 07:12 UTC, merged