[MOB-1684] 체크박스 구현
channel-io/bezier-compose pull request #47
Opened 2024-07-31 14:30 UTC by vvvvvoin

v2 체크박스를 구현합니다.
<img width="740" alt="image" src="https://github.com/user-attachments/assets/2072bbb1-19a8-49b2-9297-0377585bf971">

2024-08-01 04:37 UTC, sodp5 requested changes

2024-08-01 04:37 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/checkbox/BezierCheckbox.kt
> +                            .background(iconColor),
```suggestion
                            .background(BgWhiteNormal),
```
여기는 아이콘 컬러랑 다르네요!
<img width="220" alt="image" src="https://github.com/user-attachments/assets/ebbd7683-fa4e-4b3b-bba3-75c13c96ceaa">

2024-08-01 04:37 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/checkbox/BezierCheckbox.kt
> +) {
여기 내부에서 Varaint 별로 composable 분리하면 어떤가요??
조건이 조금 복잡해서 잘 안읽히는것 같아요
특히 CheckBold 표시하는 쪽..?

primary, secondary로 구분하면 아래 블럭으로 조건이 간편해지지 않을까 싶습니당
```
when (status) {
}
```

2024-08-01 04:37 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/checkbox/properties/BezierCheckboxVariant.kt
> +) {
primary일 때랑 secondary 일 때랑 아이콘 크기가 다른것 같아요

primary -> 16
secondary -> 20
현재는 16으로 통일되어 있음

2024-08-01 04:37 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/checkbox/BezierCheckbox.kt
> +) {
Status가 맨 위로 가게 두면 어떨까요?
사용할 때 조건이 맨 위에 있으면 좋을것 같아서요!

추가로, 편의 함수 느낌으로 status 대신 checked: Boolean (Status.[True, False])
가 있는 함수 하나 추가해주면 좋을 것 같아요

처음에는 편의성 함수는 제공할 필요가 없지 않나 생각했는데 막상 컴포넌트를 만드니까 있는 게 사용할 때 훨씬 편할것 같더라구요

어떤 경우에 편의성 함수를 제공할지 기준을 정하기는 어렵긴 한데 checkbox는 true, false로 사용하는 케이스가
더 많지 않을까 싶어서요

예시로 Avatar는 url 케이스 넣어두었고
<img width="557" alt="image" src="https://github.com/user-attachments/assets/049755ca-ed48-47a6-80e7-1a59ad143960">

iconButton은 보통 icon만 쓰일거라고 해서 icon 케이스 만들었어요
<img width="438" alt="image" src="https://github.com/user-attachments/assets/acf90c0f-3e77-4049-980d-534300396482">

2024-08-01 04:37 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/checkbox/BezierCheckbox.kt
> +                },
이거 빼면 어떨까요?

클릭 영역이 따로따로 보이는 게 어색한거 같아요 바깥만 있어도 되지 않을까 싶은!

2024-08-02 04:09 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/checkbox/BezierCheckbox.kt
> +                            .background(iconColor),
이거 아닌가요!?
<img width="723" alt="image" src="https://github.com/user-attachments/assets/71300c89-34d8-4440-8a89-3e0a3ec7b76b">

2024-08-02 04:34 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/checkbox/BezierCheckbox.kt
> +                },
넣은 이유는 텍스트가 없는 상태에서 체크박스를 사용할 경우를 가정했는데요.
CheckboxControl 영역을 클릭하면 사각형으로 리플이 생기는 모습이 어색해서 별도로 click을 주었습니다.
텍스트로 여부를 구분할까요? 아님 그냥 제거?

지금보니 secondary일 경우 indent에도 클릭이 가능한데 요건 수정해볼 필요는 있겠네요.

https://github.com/user-attachments/assets/8afe1af6-581d-4066-bcb0-a4840e0e9d07

2024-08-02 07:33 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/checkbox/BezierCheckbox.kt
> +                },
텍스트가 없는 상태는 생각해보지 못했는데, 텍스트 여부를 구분해서 처리하면 더 미려하겠네요!
전 좋은것 같습니당

indent 있을때도 수정되면 좋겠네용

2024-08-02 07:38 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/checkbox/BezierCheckbox.kt
> +                            .background(iconColor),
디자인 상으로는 이 부분을 아이콘으로 보는게 아니라 `흰 배경 + 테두리` 로 보기 때문에 bg 컬러가 들어간것 아닐까 싶네용
사소한것 같아서 잘 모르겠긴 한데 아래 방법 중 하나로 해두면 좋을것 같네욥
- 피그마랑 동일하게 맞추기
- 주석 달아두기
- 컴포넌트 피드백하기
- 그냥 두기
<img width="993" alt="image" src="https://github.com/user-attachments/assets/a5eb1c8a-ecd2-4c1d-8858-acb91c04a23e">

2024-08-02 07:59 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/checkbox/BezierCheckbox.kt
> +                            .background(iconColor),
착각했네욥..!

2024-08-02 08:34 UTC, sodp5 approved these changes

2024-08-02 08:34 UTC, merged