[MOB-1086] FloatingIconButton 추가
channel-io/bezier-compose pull request #50
Opened 2024-08-06 02:51 UTC by sodp5

FloatingIconButton을 추가합니다.

피그마: https://www.figma.com/design/8J76noM3T1Sp5cNPhnYQiG/Action?node-id=112-8902&t=d1o5negRONlPFPoV-4
노션: https://www.notion.so/channelio/Floating-Icon-Button-67109e4966bf4f0ea8ddbb5ac9834ab8?pm=c

![image](https://github.com/user-attachments/assets/5c2f3b31-7cb5-4829-9b57-20973083b05a)

2024-08-26 04:47 UTC, vvvvvoin requested changes

2024-08-26 04:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/properties/BezierFloatingIconButtonColor.kt
> +                    contentColor = { BezierTheme.colorSchemes.fgAbsoluteWhiteDark },
fgWhiteNormal인거 같은데 확인 부탁드려요

2024-08-26 04:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/properties/BezierFloatingIconButtonColor.kt
> +                    contentColor = { BezierTheme.colorSchemes.fgBlackDarkest },
```suggestion
                    contentColor = { BezierTheme.colorSchemes.fgBlackDarker },
```

2024-08-26 04:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/properties/BezierFloatingIconButtonColor.kt
> +                    contentColor = { BezierTheme.colorSchemes.fgBlackDarker },
```suggestion
                    contentColor = { BezierTheme.colorSchemes.fgBlackDark },
```

2024-08-26 04:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/properties/BezierFloatingIconButtonSize.kt
> +enum class BezierFloatingIconButtonSize(
스퀘어 타입이 없어서 radius는 제거해도 될거 같네요

2024-08-26 04:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/properties/BezierFloatingIconButtonSize.kt
> +        internal val avatarSize: BezierAvatarSize,
아이콘 버튼이라서 이모지, 아바타는 별도로 가져가는게 맞지 않나요?

2024-08-26 04:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/BezierFloatingIconButton.kt
> +            modifier = modifier
외부 modifier로 사이즈가 변경될 수 있어서 BezierFloatingIconButtonSize에 사이즈를 명시해서  requredSize를 하거나 다른 방법을 필요로할거 같아요

2024-08-26 04:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/BezierFloatingIconButton.kt
> +        Row(
래퍼의 역할이니 Row보다 Box가 어떠신가유?
```suggestion
        Box(
```

2024-08-26 04:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/BezierFloatingIconButton.kt
> +                verticalAlignment = Alignment.CenterVertically,
```suggestion
```

2024-08-26 04:47 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/properties/BezierFloatingIconButtonSize.kt
임포트 최적화 부탁드려요

2024-08-29 11:11 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/properties/BezierFloatingIconButtonColor.kt
> +                    contentColor = { BezierTheme.colorSchemes.fgAbsoluteWhiteDark },
진짜 매의 눈이네요 와우..

2024-08-29 11:23 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/floating_icon_button/properties/BezierFloatingIconButtonSize.kt
> +        internal val avatarSize: BezierAvatarSize,
프로퍼티명이 contents면 슬롯으로 보는게 맞다고 하시더라구요! 이 부분 유지해뒀다가 슬롯관련 작업할 때 한번에 바꿔둘게요

2024-09-03 07:08 UTC, merged