[MOB-1781] AvatarGroup 추가
channel-io/bezier-compose pull request #58
Opened 2024-08-12 04:41 UTC by sodp5

AvatarGroup을 추가합니다.

피그마: https://www.figma.com/design/aJJF4bU82uR0jAsmWp5wlE/Navigation?node-id=10-24759&t=QksnbB4apeZ32m5g-4
노션: https://www.notion.so/channelio/Avatar-Group-5fa6501554514acb816f3ff8ad0f7c91?pvs=4

<img width="401" alt="image" src="https://github.com/user-attachments/assets/dd528eaf-08e9-4007-8b26-8d5ecb0c756c">

2024-08-12 07:22 UTC, vvvvvoin requested changes

2024-08-12 07:22 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        }
아이콘 사이즈가 16 고정이면 아바타 사이즈에 따른 조정이 안될거 같은데 따로 요청드려야할 수도?

2024-08-12 07:22 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar_group/BezierAvatarGroup.kt
> +fun BezierAvatarGroup(
피그마에 공통에 72, 120 이 있는데 추가하시나요?

2024-08-12 07:46 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        }
사용되는거만 넣어두셨다고 하셨길래 그냥 고정으로 뒀어요
다른 사이즈는 고려하지 않는듯 합니다!
https://desk.channel.io/root/threads/groups/(CT)BezierRedesign-244958/66b4583243ebb3da000f/66b4583243ebb3da000f

2024-08-12 07:47 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar_group/BezierAvatarGroup.kt
> +fun BezierAvatarGroup(
여기도 위 코멘트랑 비슷한데요
소스에는 있긴한데 마찬가지로 정의된 건 하나뿐이라 하나만 두려합니다 
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/f0c0f598-8ab5-40f4-b2f3-d35db3e3de00">

2024-08-12 14:29 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        isEllipsis: Boolean = false,
피그마에 존재하는 속성값이면 기본값을 안주기로 했는데, 사실상 저희 편의상으로 기준을 나누는게 좀 더 맞을거 같네요..?

2024-08-12 14:29 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        }
이전에 저희 논의중에서 의도되지 않거나 나올 수 없는 경우는 최대한 방지하자를 생각하면 조건에 사이즈도 들어가야하는데 진짜 진짜 잘 모르겠습니다.

2024-08-12 14:34 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        }
그거면 현재 구현이 올바르지 않나요??
"이상하게 나오는 건 괜찮은데 아예 안나오게만 하지말자" 였던거 같아서용

2024-08-12 14:35 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        isEllipsis: Boolean = false,
그것도 그렇네요 🤔 
일단 저는 너무 안넣을것만 같은 케이스만 기본값 주고 있었는데 말씀주신대로
작업자 판단의 편의상 기준이라고 봐야겠네요

2024-08-13 05:28 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        isEllipsis: Boolean = false,
기조는 기본값은 일반적으로 없다라고 생각하고 리뷰하면서 핑퐁해도 좋을거 같네요.

2024-08-13 05:30 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        }
체크박스할 때 intermidate 타입일 때 그냥 false로 폴백처리한 것 처럼 이것도 폴백으로 가져주는거 아닌가 생각했어요.

2024-08-21 07:38 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/avatar/BezierAvatar.kt
> +        }
정기싱크 때 얘기한것처럼 24가 아니면 invalid 하다고 판단하여 아예 안보이게 했습니다!

2024-08-26 04:17 UTC, vvvvvoin approved these changes

2024-08-26 04:17 UTC, merged