[MOB-1873] 이모지 토글 버튼 추가
channel-io/bezier-compose pull request #66
Opened 2024-08-22 04:15 UTC by vvvvvoin

<img width="552" alt="image" src="https://github.com/user-attachments/assets/7fe9b607-7d69-4b1d-a104-84657964535c">

피그마 : https://www.figma.com/design/fPXP9zfjZU9NyARnhTWL6o/Input?node-id=543-145&t=WDIP1n5b9DcYgACa-1

2024-09-04 06:52 UTC, sodp5 requested changes

2024-09-04 06:52 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/toggle_emoji_button/BezierToggleEmojiButton.kt
> +        onClick: () -> Unit,
onClick 매개변수를 위로 올리는 게 매개변수 순서상 좀 더 일관된다는 느낌을 받는데 어떻게 생각하시나요??

아래 문서에는, trailing lambda가 있는 경우 Composable로 오인할 수 있다.
라는 내용으로 근거삼고 있긴 하네용 Layout 쓰는 경험 생각해보면 그럴 수 있을것 같기도 해요
https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-component-api-guidelines.md#parameters-order

2024-09-04 10:13 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/toggle_emoji_button/BezierToggleEmojiButton.kt
> +        onClick: () -> Unit,
아 이건 잘못 쓴게 완전 맞습니다ㅋㅋㅋㅋ

2024-09-09 05:58 UTC, sodp5 approved these changes

2024-09-09 05:58 UTC, merged