[MOB-2039] Badge 추가
channel-io/bezier-compose pull request #76
Opened 2024-09-24 07:27 UTC by sodp5

뱃지를 추가합니다.

<img width="620" alt="image" src="https://github.com/user-attachments/assets/1da47ea4-5fa9-4880-ad98-b907796d2c60">

피그마: https://www.figma.com/design/5ApmwcPEG8G8rI2i6SpAkZ/Feedback?node-id=131-25403&t=rvZ1MM1LGIyiJ9F5-4

2024-09-24 07:48 UTC, vvvvvoin requested changes

2024-09-24 08:03 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/BezierBadge.kt
> +) {
icon으로 되어있으면 진짜 icon인거로 했어서 슬롯은 아닌것 같아요!

우측에 들어갈 수 있는지는 몰랐네요..! 추가해두었습니다

2024-09-24 08:03 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/badge/properties/BezierBadgeColor.kt
> +            contentColor = { BezierTheme.colorSchemes.fgOrangeDark },
주디도 비슷한 말씀 하신 적 있긴한데요..ㅋㅋㅋ 이건 나중에 수정이 어떻게 되냐에 따라 좀 다를것 같긴 하네요

2024-09-25 07:22 UTC, vvvvvoin approved these changes

2024-09-25 07:22 UTC, merged