[MOB-2068] Switch 컴포넌트 구현
channel-io/bezier-compose pull request #80
Opened 2024-09-29 05:26 UTC by sodp5

Switch 컴포넌트를 구현합니다.
- 상태가 현재 컴포넌트 상태와 맞지 않는다면 10초의 딜레이 이후 원래 상태로 되돌아갑니다.
- 상태가 되돌아가는 경우는 상태가 변경되었다는 callback을 주지 않습니다

코드 의도를 간략하게 남겨보면
- Control 에는 순수하게 on/off 의 역할을 부여했습니다.
- 되돌아가는 로직은 Control이 아닌 Switch에 부여했습니다.
Control은 좀 더 순수한 단위라고 생각되어서 UI를 표시하는 것 이외의 로직을 넣지 않으려 했습니다

<img width="313" alt="image" src="https://github.com/user-attachments/assets/952fbb9f-6e25-40d2-883b-3d4af11f9b56">

2024-09-29 05:28 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/source/BezierSwitchControl.kt
> +                    .clickable(
외부 padding 대신에 실제 차지하는 너비를 넣고 싶었는데 SwitchWidth를 베이스로 계산해야하는 공식이 있어서 외부 padding을 넣었습니다 😢

(외부 padding을 사이즈에 포함시키면 계산식이 좀 더 난잡해져서..)

2024-10-04 07:53 UTC, vvvvvoin requested changes

2024-10-04 07:53 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/source/BezierSwitchControl.kt
> +    }
thumb를 라인으로 그린다는게 어색할 수 있을거 같다는 생각이 들어서 그러는데 drawRoundRect로 하는 좋은 아이디어가 있는데 어떠신가요? 
```suggestion
    Canvas(
            modifier = Modifier
                    .size(ThumbSize)
                    .bezierShadow(ShadowStyle.Shadow2, CircleShape),
    ) {
        drawRoundRect(
                color = color,
                topLeft = Offset(thumbValue.invoke(), 0f),
                cornerRadius = CornerRadius(100f, 100f)
        )
```

2024-10-04 07:53 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/source/BezierSwitchControl.kt
> +    }
이 전체가 Thumb로 보이는데 box안에 thumb가 있는게 어색하지 않을까 한번 생각해봤는데 어떻게 생각하시나요?

2024-10-04 07:53 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/BezierSwitch.kt
> +    val currentOnCheckedChange by rememberUpdatedState(onCheckedChange)
currentOnCheckedChange 의 용도가 궁금합니다

2024-10-04 07:53 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/source/BezierSwitchControl.kt
이 파일 프리뷰가 안보이는데 저만 그런가용?

2024-10-04 09:20 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/source/BezierSwitchControl.kt
> +    }
음 이렇게 구현하면 좀 다른부분을 바꿔야하는군요 흠흠

2024-10-04 09:35 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/source/BezierSwitchControl.kt
> +}
말씀 주신 의도가 맞긴 합니다
굳이 안쪽에서 라운드를 바깥이랑 맞춰야할 필요가 있나 싶어서요!

바깥의 값이 바뀌면 안의 값도 바꿔줘야하는데 굳이 맞추거나, 상수를 추가하는 것 보다는 외부에 의존적인 게 더 낫다고 생각했어요

2024-10-04 09:41 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/BezierSwitch.kt
넵 이건 일단 없이 구현해뒀어요 근데 현재 기준 애니메이션 도중에는 다시 못바꾸긴 해요 (리뷰 받으려고 여기까지만 끊어서 작업했습니다)

2024-10-04 09:41 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/BezierSwitch.kt
만약 하게된다면, 논의 후에 아예 다른 pr로 작업 할게요

2024-10-07 04:08 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/source/BezierSwitchControl.kt
> +    }
좋은데요?

2024-10-07 04:08 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/BezierSwitch.kt
> +    val currentOnCheckedChange by rememberUpdatedState(onCheckedChange)
요거 필요 없었네요 생각을 잘못했군요 😢

2024-10-07 04:08 UTC, sodp5 commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/source/BezierSwitchControl.kt
넵 전 잘보임요 ㅋㅋㅋ

2024-10-07 15:02 UTC, vvvvvoin commented on bezier/src/main/java/io/channel/bezier/compose/component/switch/source/BezierSwitchControl.kt
> +    }
요 부분은 파일을 별도로 분리하는건 어떠신가요?!

2024-10-15 04:49 UTC, vvvvvoin approved these changes

2024-10-15 04:50 UTC, merged